/*
-- Query: SELECT * FROM webveiculos.carros
LIMIT 0, 1000

-- Date: 2022-12-21 19:23
*/
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (1,'Toyota Camry',30000.00,'Carro','BRA2E19','2008','/img/img_Inicial/Camry.png','Aquecimento dos bancos dianteiros, ar-condicionado digital 3-zone e multimídia 9\" com 6 alto-falantes e conexão com Android Auto® e Apple CarPlay',1,1,1);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (2,'Volvo C40',99999.99,'Carro','EUA3214','2012','/img/img_Inicial/Volvo.png','O segmento dos SUVs é aquela badalada festa que ninguém quer ficar de fora. Isso inclui o Volvo XC40 2022, o modelo de entrada da marca sueca que, assim como o restante da linha, aposta apenas em vers',2,2,2);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (3,'Fiat Pulse',99999.99,'Carro','BRA1324','2016','/img/img_Inicial/Pulse.png','Fundada em 1977 e adquirida pelo Banco Itaú S/A em 2003, a Fiat Administradora de Consórcios Ltda.',2,6,6);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (4,'Nissan Sentra',92000.00,'Carro','PRR5522','2020','/img/img_Inicial/Sentra.png','Importado do México, o Sentra 2021 era encontrado nas versões de acabamento S, SV e SL. Todas elas saem de fábrica com um motor 2.0 litros flex de até 140 cavalos de potência, atrelado a uma transmiss',1,4,5);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (5,'Honda Civic',99999.99,'Carro','ALG1123','2018','/img/img_Inicial/Civic.png',' quando abastecido com etanol. Já a topo de linha recebe o 1.5 turbo de 173 cv de potência.',4,3,1);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (6,'Gol',95000.00,'Carro','RJC6900','2020','/img/img_Inicial/Gol.png','specificações técnicas, itens de série, opcionais, acabamento interno, cores e preços estão sujeitos a alterações sem aviso prévio pela Volkswagen do Brasil.',4,2,4);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (7,'Triumph Tiger 900',99999.99,'Moto','SSD2289','2019','/img/img_Inicial/Tiger.png','Um novo nome para uma geração: a família Tiger 900 representa um salto qualitativo em termos de funcionalidade, com duas séries que revelam um mundo de aventuras urbanas, jornadas de longa distância e',7,2,8);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (8,'Honda Nc 750X',60000.00,'Moto','ADD4040','2022','/img/img_Inicial/Nc-750X.png','Com 802 mm, a altura do assento da nova NC 750X foi reduzida em 30 mm em relação à versão anterior e, combinada ao guidão mais elevado, garante uma posição de pilotagem mais vertical e confortável, al',8,4,3);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (9,'Honda CB500X',99999.99,'Moto','WAS3232','2021','/img/img_Inicial/CB500.png','O design da nova CB 500X destaca-se da multidão com seu estilo compacto de crossover e um toque robusto e agressivo. Novas cores e gráficos vibrantes são o complemento perfeito para a nova e robusta s',9,1,3);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (10,'Kawasaki Ninja 300',55000.00,'Moto','MNM1023','2018','/img/img_Inicial/Ninja.png','Quando se trata de desempenho, tecnologia e design, o nome “Ninja” representa o melhor que a Kawasaki tem a oferecer. No caso da  Ninja 300, significa um motor bicilíndrico de 296 cc com potência e to',10,4,9);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (11,'Yamaha XMA',68000.00,'Moto','MES2020','2021','/img/img_Inicial/Xmax.png','Se por um lado Darth Vader é parte humano, parte robô, essa edição limitada é 100% máquina.',9,5,10);
INSERT INTO `` (`idCarro`,`Nome`,`Valor`,`Modelo`,`Placa`,`Ano`,`Imagem`,`Descricao`,`Categorias_idCategorias`,`Pedidos_idPedidos`,`Marcas_idMarcas`) VALUES (12,'Yamaha MT09',72000.00,'Moto','LKS1478','2020','/img/img_Inicial/MT09.png','Com apenas 193 kg, 115 cv e 8,92 kgf.m de torque, a MT-09 surpreende em todos os detalhes. Seu motor crossplane tricilíndrico de 847 cc proporciona acelerações e retomadas rápidas de uma autêntica Mas',9,3,10);
